spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.23:3306/pbl?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: pbl
    password: pbl
    type: com.alibaba.druid.pool.DruidDataSource
   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.jk.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
